apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: postgres
